[package]
name = "rtask"
version = "0.1.5"

edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
console = "0.15.11"
dialoguer = "0.11.0"
dirs = "6.0.0"
rusqlite = {version =  "0.36.0", features = ["bundled"]}
tui = "0.19.0"
uuid = {version =  "1.17.0", features = ['v4']}
