name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  clippy-check:
    name: Run cargo clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Clippy (fail on warnings)
        run: cargo clippy -- -D warnings
